# Generated by Django 3.0.3 on 2020-02-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_type',
            fields=[
                ('type_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
    ]
