# Generated by Django 3.0.3 on 2020-02-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200227_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='lmage_id',
            new_name='image_id',
        ),
    ]
